//
//  UIConstants.h
//  Abacus
//
//  Created by Anil K Nellutla on 4/19/14.
//  Copyright (c) 2014 Anil K Nellutla. All rights reserved.
//

#ifndef Abacus_UIConstants_h
#define Abacus_UIConstants_h

#endif

#define ABACUS_VIEW_ORIGIN_X_OFFSET 3
#define ABACUS_VIEW_WIDTH_SCALE_FACTOR 0.97
#define ABACUS_VIEW_HEIGHT_SCALE_FACTOR 0.50
#define ABACUS_VIEW_OFFSET_FROM_BASE 1

#define NUMBER_VIEW_ORIGIN_X_OFFSET 3
#define NUMBER_VIEW_WIDTH_SCALE_FACTOR 0.97
#define NUMBER_VIEW_HEIGHT_SCALE_FACTOR 0.04
#define NUMBER_VIEW_OFFSET_FROM_ABACUS_VIEW 1

#define ABACUS_VALUE_VIEW_ORIGIN_X_OFFSET 3
#define ABACUS_VALUE_VIEW_WIDTH_SCALE_FACTOR 0.97
#define ABACUS_VALUE_VIEW_HEIGHT_SCALE_FACTOR 0.04
#define ABACUS_VALUE_VIEW_OFFSET_FROM_NUMBER_VIEW 1

#define COLUMN_BEAD_WIDTH_RATIO 0.62
#define COLUMN_BEAD_HEIGHT_RATIO 0.52

#define BEAD_GAP 2

