//
//  UIConstants.h
//  Abacus
//
//  Created by Anil K Nellutla on 4/19/14.
//  Copyright (c) 2014 Anil K Nellutla. All rights reserved.
//

#ifndef Abacus_UIConstants_h
#define Abacus_UIConstants_h

#endif

#define ABACUS_VIEW_ORIGIN_X_OFFSET 3
#define ABACUS_VIEW_WIDTH_SCALE_FACTOR 0.99
#define ABACUS_VIEW_HEIGHT_SCALE_FACTOR 0.55
#define ABACUS_VIEW_OFFSET_FROM_BASE 1
#define ABACUS_VIEW_BORDER_SIZE 20

#define NUMBER_VIEW_ORIGIN_X_OFFSET 3
#define NUMBER_VIEW_WIDTH_SCALE_FACTOR 0.99
#define NUMBER_VIEW_HEIGHT_SCALE_FACTOR 0.04
#define NUMBER_VIEW_OFFSET_FROM_ABACUS_VIEW 1

#define ABACUS_VALUE_VIEW_ORIGIN_X_OFFSET 3
#define ABACUS_VALUE_VIEW_WIDTH_SCALE_FACTOR 0.99
#define ABACUS_VALUE_VIEW_HEIGHT_SCALE_FACTOR 0.01
#define ABACUS_VALUE_VIEW_OFFSET_FROM_NUMBER_VIEW 1

#define CALCULATOR_VIEW_ORIGIN_X_OFFSET 3
#define CALCULATOR_VIEW_HEIGHT_SCALE_FACTOR 0.38
#define CALCULATOR_VIEW_OFFSET_FROM_ABACUS_VALUE_VIEW 1
#define CALCULATOR_VIEW_WIDTH_SCALE_FACTOR 0.30

#define CALCULATOR_DIGIT_DISPLAY_HEIGHT_SCALE_FACTOR 0.25

#define CALCULATOR_DIGIT_BUTTONS_ROWS 4
#define CALCULATOR_DIGIT_BUTTONS_COLUMNS 4

#define COLUMN_BEAD_WIDTH_RATIO 0.69
#define COLUMN_BEAD_HEIGHT_RATIO 0.59

#define ROW_VIEW_HEIGHT 8

#define COLUMN_WIDTH 4

#define BEAD_GAP 2

